spring:
  application:
    name: forum
  datasource:
    url: jdbc:mysql://localhost/forum
    username: root
    password: caelum
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
  rabbitmq:
    host: 192.168.1.9
    port: 5672
    username: guest
    password: guest